---

- name: Install vim
  yum: name=vim state=installed

- name: Install tmux
  yum: name=tmux state=installed

- name: Install mosh dependencies
  action: yum pkg={{item}} state=installed
  with_items:
    - protobuf-devel
    - ncurses-devel
    - zlib-devel
    - openssl-devel 

- name: Create vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Create tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Clone mosh repository from GitHub
  git:
    repo: https://github.com/mobile-shell/mosh.git
    dest: ~/mosh

- name: Register mosh-server
  stat:
    path: /usr/local/bin/mosh-server
  register: mosh_server_binary

- name: Compile mosh
  shell: |
    ./autogen.sh
    ./configure
    make
    make install
    mosh-server
  args:
    chdir: ~/mosh
  when: not mosh_server_binary.stat.exists

# TODO: Start tmux
