---

- name: Install packages
  action: yum pkg={{item}} state=installed
  with_items:
    - vim
    - git
    - tmux

- name: Create vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Create tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf


# TODO: Start tmux
